# Generated by Django 4.1.7 on 2023-04-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpark_id', models.CharField(max_length=5)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=50)),
                ('lots_available', models.SmallIntegerField(blank=True, default=0)),
                ('total_lots', models.SmallIntegerField(blank=True, default=0)),
                ('lot_type', models.CharField(blank=True, max_length=1)),
                ('agency', models.CharField(blank=True, max_length=3)),
                ('parking_system', models.CharField(blank=True, max_length=50)),
                ('short_term_parking', models.TextField(blank=True)),
                ('free_parking', models.TextField(blank=True)),
                ('night_parking', models.TextField(blank=True)),
                ('apitofetch', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['carpark_id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('blacklist', models.ManyToManyField(related_name='blacklist', to='ParkApp.carpark')),
                ('favouritesList', models.ManyToManyField(related_name='favourites', to='ParkApp.carpark')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCarpark',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('carpark_id', models.CharField(max_length=5)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=50)),
                ('lots_available', models.SmallIntegerField(blank=True, default=0)),
                ('total_lots', models.SmallIntegerField(blank=True, default=0)),
                ('lot_type', models.CharField(blank=True, max_length=1)),
                ('agency', models.CharField(blank=True, max_length=3)),
                ('parking_system', models.CharField(blank=True, max_length=50)),
                ('short_term_parking', models.TextField(blank=True)),
                ('free_parking', models.TextField(blank=True)),
                ('night_parking', models.TextField(blank=True)),
                ('apitofetch', models.CharField(blank=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical carpark',
                'verbose_name_plural': 'historical carparks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkApp.question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='carpark',
            constraint=models.UniqueConstraint(fields=('carpark_id', 'lot_type'), name='carpark primary key combination'),
        ),
    ]
