# Generated by Django 4.1.7 on 2023-04-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carpark',
            name='carpark primary key combination',
        ),
    ]
