# Generated by Django 4.1.7 on 2023-03-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ParkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=50)),
                ('availableLots', models.SmallIntegerField(default=0)),
                ('totalLots', models.SmallIntegerField(default=0)),
                ('lotType', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=3)),
                ('parkingSystem', models.CharField(max_length=50)),
                ('shortTermParking', models.TextField()),
                ('freeParking', models.TextField()),
                ('nightParking', models.TextField()),
                ('APItoFetch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCarpark',
            fields=[
                ('id', models.CharField(db_index=True, max_length=4)),
                ('address', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=50)),
                ('availableLots', models.SmallIntegerField(default=0)),
                ('totalLots', models.SmallIntegerField(default=0)),
                ('lotType', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=3)),
                ('parkingSystem', models.CharField(max_length=50)),
                ('shortTermParking', models.TextField()),
                ('freeParking', models.TextField()),
                ('nightParking', models.TextField()),
                ('APItoFetch', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical carpark',
                'verbose_name_plural': 'historical carparks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
