# Generated by Django 4.1.7 on 2023-04-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0002_remove_carpark_carpark primary key combination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
