# Generated by Django 4.1.7 on 2023-04-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0003_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favouritesList',
            new_name='favourites',
        ),
    ]
