# Generated by Django 4.1.4 on 2023-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ParkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('blacklist', models.ManyToManyField(blank=True, related_name='blacklisted_by_user', to='ParkApp.carpark')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorited_by_user', to='ParkApp.carpark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
