# Generated by Django 4.1.4 on 2023-04-09 13:39

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpark_id', models.CharField(max_length=5)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=50)),
                ('lots_available', models.SmallIntegerField(blank=True, default=0)),
                ('total_lots', models.SmallIntegerField(blank=True, default=0)),
                ('lot_type', models.CharField(blank=True, max_length=1)),
                ('agency', models.CharField(blank=True, max_length=3)),
                ('parking_system', models.CharField(blank=True, max_length=50)),
                ('short_term_parking', models.TextField(blank=True)),
                ('free_parking', models.TextField(blank=True)),
                ('night_parking', models.TextField(blank=True)),
                ('apitofetch', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['carpark_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCarpark',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('carpark_id', models.CharField(max_length=5)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=50)),
                ('lots_available', models.SmallIntegerField(blank=True, default=0)),
                ('total_lots', models.SmallIntegerField(blank=True, default=0)),
                ('lot_type', models.CharField(blank=True, max_length=1)),
                ('agency', models.CharField(blank=True, max_length=3)),
                ('parking_system', models.CharField(blank=True, max_length=50)),
                ('short_term_parking', models.TextField(blank=True)),
                ('free_parking', models.TextField(blank=True)),
                ('night_parking', models.TextField(blank=True)),
                ('apitofetch', models.CharField(blank=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical carpark',
                'verbose_name_plural': 'historical carparks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
