# Generated by Django 4.1.4 on 2023-04-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCarpark',
        ),
    ]
